ICE:
  occurrence: 0.3
  science_value: 0.1
  density: 997 # kg/m^3
  color: {r: 0, g: 0, b: 30}
  # color: {r: 0, g: 0, b: 255}

SALT:
  occurrence: 0.6
  science_value: 0.4
  density: 0 # TODO
  # color: {r: 231, g: 231, b: 245}
  color: {r: 100, g: 95, b: 90} # orange peaks in atacama_y1a image
  # color: {r: 255, g: 0, b: 0}

HYDRATES:
  occurrence: 0.1
  science_value: 0.8
  density: 0 # TODO
  color: {r: 0, g: 60, b: 0}
  # color: {r: 0, g: 255, b: 0}

VOID:
  occurrence: 0.1
  science_value: 0.8
  density: 0 # TODO
  color: {r: 0, g: 0, b: 0}
