ICE:
  occurrence: 0.3
  science_value: 0.1
  density: 997 # kg/m^3
  reference_color: {r: 0, g: 0, b: 30}
  # reference_color: {r: 0, g: 0, b: 255}
  visualize_color: {r: 120, g: 120, b: 255}


SALT:
  occurrence: 0.6
  science_value: 0.4
  density: 0 # TODO
  reference_color: {r: 100, g: 95, b: 90} # orange peaks in atacama_y1a image
  # reference_color: {r: 255, g: 0, b: 0}
  visualize_color: {r: 250, g: 50, b: 100}

HYDRATES:
  occurrence: 0.1
  science_value: 0.8
  density: 0 # TODO
  reference_color: {r: 0, g: 60, b: 0}
  # reference_color: {r: 0, g: 255, b: 0}
  visualize_color: {r: 110, g: 255, b: 180}
